# Stage 1: Build React app
FROM node:14-alpine as build
WORKDIR /app
COPY furonten/package*.json ./
RUN npm ci --silent
COPY furonten ./
RUN npm run build

# Stage 2: Serve React app with Nginx
FROM nginx:1.21-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
